version: "3.4"

services:
  app:
    build: ..
    working_dir: /application
    volumes:
      - ../:/application
      - node_modules:/application/node_modules
    expose:
      - 3000
    environment:
      APPLICATION: "roo-ui"
      CI: "true"
      TZ: "Australia/Sydney"
      BUILDKITE_BUILD_CREATOR_EMAIL:
      BUILDKITE_BUILD_CREATOR:
      BUILDKITE_BUILD_NUMBER:
      BUILDKITE_COMMIT:
      NPM_TOKEN:

volumes:
  node_modules:
