version: '3.4'

services:
  app:
    build: ..
    working_dir: /application
    volumes:
      - ../:/application
      - node_modules:/application/node_modules
    expose:
      - 3000
    environment:
      CI: 'true'
      TZ: 'Australia/Sydney'
      APPLICATION:
      BUILDKITE_BUILD_CREATOR_EMAIL:
      BUILDKITE_BUILD_CREATOR:
      BUILDKITE_BUILD_NUMBER:
      BUILDKITE_COMMIT:
      GITHUB_TOKEN:
      NPM_TOKEN:

volumes:
  node_modules:
