version: '3.4'

services:
  app:
    build: ..
    working_dir: /application
    environment:
      CI: 'true'
      TZ: 'Australia/Sydney'
      APPLICATION:
      BUILDKITE_BUILD_CREATOR_EMAIL:
      BUILDKITE_BUILD_CREATOR:
      BUILDKITE_BUILD_NUMBER:
      BUILDKITE_COMMIT:
      GITHUB_TOKEN:
      NPM_TOKEN:
