steps:
  - label: ':git: Commit message'
    command: ./hooroo-ci/scripts/commitmsg
    env:
      BUILDKITE_FIG_CONTAINER: app
    agents:
      ci-env: production
  - label: ':eslint: Lint'
    command: ./hooroo-ci/scripts/lint
    env:
      BUILDKITE_FIG_CONTAINER: app
    agents:
      ci-env: production
  - label: ':jest: Test'
    command: ./hooroo-ci/scripts/test
    env:
      BUILDKITE_FIG_CONTAINER: app
    agents:
      ci-env: production
  - wait
  - label: ':npm: Publish'
    command: ./hooroo-ci/scripts/publish
    branches: 'master'
    concurrency: 1
    concurrency_group: 'roo-ui/publish'
    env:
      BUILDKITE_FIG_CONTAINER: app
    agents:
      ci-env: production
  - label: ':storybook: Deploy'
    command: ./hooroo-ci/scripts/storybook
    branches: 'master'
    concurrency: 1
    concurrency_group: 'roo-ui/deploy'
    env:
      BUILDKITE_FIG_CONTAINER: app
    agents:
      ci-env: production
