.defaults: &defaults
  agents:
    ci-env: production
  plugins:
    docker-compose#v2.5.1:
      run: app
      config: .buildkite/docker-compose.yml

.deploy_defaults: &deploy_defaults
  <<: *defaults
  branches: master
  concurrency: 1
  concurrency_group: roo-ui/publish

env:
  BUILDKITE_CLEAN_CHECKOUT: true

steps:
  - name: ':docker: Build'
    <<: *defaults
    plugins:
      ecr#v1.1.4:
        login: true
        no-include-email: true
      docker-compose#v2.5.1:
        build: app
        config: .buildkite/docker-compose.yml

  - wait

  - name: ':eslint: Lint'
    <<: *defaults
    command: yarn run lint

  - name: ':jest: Test'
    <<: *defaults
    command: yarn run test

  - wait

  - name: ':npm: Publish'
    <<: *deploy_defaults
    command: scripts/publish

  - name: ':storybook: Deploy'
    <<: *deploy_defaults
    command: yarn deploy-storybook
