#!/bin/bash -eu

git config --global user.email "$BUILDKITE_BUILD_CREATOR_EMAIL"
git config --global user.name "$BUILDKITE_BUILD_CREATOR"

yarn build-storybook
yarn deploy-storybook --ci --existing-output-dir=storybook-static --host-token-env-variable=GITHUB_TOKEN
