declare module 'roo-ui/assets' {
  export const roo: string;
  export const rooRed: string;
  export const pebble: string;
  export const pebbleRed: string;
  export const pebbleRedNarrow: string;
  export const pebbleWhite: string;
  export const alertIllustration: string;
  export const luggage: string;
  export const lightbulb: string;
  export const ribbon: string;
  export const creditCardCID: string;
  export const creditCardCVV: string;
  export const baggage: string;
  export const mail: string;
  export const laptop: string;
  export const browser: string;
  export const headset: string;
}
