#!/bin/bash -eu

git config --global user.email "$BUILDKITE_BUILD_CREATOR_EMAIL"
git config --global user.name "$BUILDKITE_BUILD_CREATOR"

git fetch && git checkout master
yarn lerna publish --conventional-commits --yes
git push origin master
